dist: xenial
services:
  - xvfb
sudo: false
language: python
jobs:
  include:
    - stage: "Tests"
    - python: 3.7
      name: "Python 3.7"
      dist: xenial
      sudo: true
      script: tox -e py37
    - python: 3.7
      name: "Coverage"
      dist: xenial
      sudo: true
      script: tox -e coverage
    - python: 3.6
      name: "Python 3.6"
      script: tox -e py36
branches:
  only:
  - master
  - develop